// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavjF4DXgnBjXZCTsyu9kpcb7FpL1GV7s',
    appId: '1:369450331438:android:97c0fbe137743cde729ebf',
    messagingSenderId: '369450331438',
    projectId: 'my-fluttermodule1',
    storageBucket: 'my-fluttermodule1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6QLGQ5n4p8ZVUbGFquivJNhecTn3C2IE',
    appId: '1:369450331438:web:7c2bd64e1db31615729ebf',
    messagingSenderId: '369450331438',
    projectId: 'my-fluttermodule1',
    authDomain: 'my-fluttermodule1.firebaseapp.com',
    storageBucket: 'my-fluttermodule1.firebasestorage.app',
    measurementId: 'G-628LS6Q2MS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7tQh2eaSrIwBJa_sroQ1uuqtNjcsHCRQ',
    appId: '1:369450331438:ios:e95d444ccf4f187d729ebf',
    messagingSenderId: '369450331438',
    projectId: 'my-fluttermodule1',
    storageBucket: 'my-fluttermodule1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7tQh2eaSrIwBJa_sroQ1uuqtNjcsHCRQ',
    appId: '1:369450331438:ios:e95d444ccf4f187d729ebf',
    messagingSenderId: '369450331438',
    projectId: 'my-fluttermodule1',
    storageBucket: 'my-fluttermodule1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6QLGQ5n4p8ZVUbGFquivJNhecTn3C2IE',
    appId: '1:369450331438:web:fa507fc958e37759729ebf',
    messagingSenderId: '369450331438',
    projectId: 'my-fluttermodule1',
    authDomain: 'my-fluttermodule1.firebaseapp.com',
    storageBucket: 'my-fluttermodule1.firebasestorage.app',
    measurementId: 'G-W4YLFHQLDG',
  );

}